# Generated by Django 4.2.30 on 2026-05-22 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('virement', 'Virement bancaire'), ('versement', 'Versement bancaire (dépôt agence)'), ('livraison', 'Paiement à la livraison')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activée')),
                ('instructions', models.TextField(verbose_name='Instructions pour le client')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='N° de compte / RIB')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='Titulaire du compte')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('virement', 'Virement bancaire'), ('versement', 'Versement bancaire'), ('livraison', 'Paiement à la livraison')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='Notes de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Reçu de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(default='Agence Venice Autocars, Casablanca', max_length=300),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_location',
            field=models.CharField(default='Agence Venice Autocars, Casablanca', max_length=300),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('awaiting_payment', 'En attente de paiement'), ('payment_submitted', 'Reçu soumis'), ('payment_verified', 'Paiement vérifié'), ('active', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
