# Generated by Django 4.2.30 on 2026-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_paymentmethod_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite de paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(default='Agence Venice Autocars - Hay Azhar Bernoussi, Casablanca', max_length=300),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_location',
            field=models.CharField(default='Agence Venice Autocars - Hay Azhar Bernoussi, Casablanca', max_length=300),
        ),
    ]
