# Generated by Django 4.2.30 on 2026-05-22 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur')], default='client', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('cin', models.CharField(blank=True, max_length=20, verbose_name='N° CIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
