# Generated by Django 4.2.30 on 2026-05-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix/jour (€)')),
                ('seats', models.IntegerField(default=5, verbose_name='Places')),
                ('doors', models.IntegerField(default=4, verbose_name='Portes')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='manual', max_length=20)),
                ('fuel', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='essence', max_length=20)),
                ('mileage', models.IntegerField(default=0, verbose_name='Kilométrage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('features', models.TextField(blank=True, verbose_name='Équipements (séparés par virgule)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Image principale')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcategory')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-created_at'],
            },
        ),
    ]
